

module.exports = (app) => {
  const { router, controller, config, middleware, } = app

  // 项目 project
  router.post('/system/project/list', controller.system.project.list)
  router.post('/system/project/add', controller.system.project.add)
  router.post('/system/project/detail', controller.system.project.detail)
  router.post('/system/project/update', controller.system.project.update)
  router.post('/system/project/delete', controller.system.project.delete)
  router.post('/system/project/refreshSystemToken', controller.system.project.refreshSystemToken)
  // 运维
  router.post('/devops/machine/info', controller.devops.machine.info)
  router.post('/devops/machine/status', controller.devops.machine.status)
  router.post('/devops/machine/loadinfo', controller.devops.machine.loadinfo)
  router.post('/devops/machine/cpuinfo', controller.devops.machine.cpuinfo)
  router.post('/devops/machine/memoryinfo', controller.devops.machine.memoryinfo)
  router.post('/devops/machine/diskinfo', controller.devops.machine.diskinfo)
  router.post('/devops/machine/networkinfo', controller.devops.machine.networkinfo)
  // docker操作
  router.post('/devops/docker/container', controller.devops.docker.container)

  // 收藏 favourite
  router.post('/system/favourite/list', controller.system.favourite.list)
  router.post('/system/favourite/do', controller.system.favourite.do)
  // 系统配置 option
  router.post('/system/option/list', controller.system.option.list)
  router.post('/system/option/add', controller.system.option.add)
  router.post('/system/option/detail', controller.system.option.detail)
  router.post('/system/option/upsert', controller.system.option.upsert)
  router.post('/system/option/update', controller.system.option.update)
  router.post('/system/option/delete', controller.system.option.delete)
  // 系统评论 comment
  router.post('/system/comment/list', controller.system.comment.list)
  router.post('/system/comment/add', controller.system.comment.add)
  router.post('/system/comment/detail', controller.system.comment.detail)
  router.post('/system/comment/update', controller.system.comment.update)
  router.post('/system/comment/delete', controller.system.comment.delete)

  // 数据字典 dictionary
  router.post('/business/dictionary/list', controller.business.dictionary.list)
  router.post('/business/dictionary/detailList', controller.business.dictionary.detailList)
  router.post('/business/dictionary/add', controller.business.dictionary.add)
  router.post('/business/dictionary/detail', controller.business.dictionary.detail)
  router.post('/business/dictionary/update', controller.business.dictionary.update)
  router.post('/business/dictionary/batchUpdate', controller.business.dictionary.batchUpdate)
  router.post('/business/dictionary/delete', controller.business.dictionary.delete)
  router.post('/business/dictionary/batchDelete', controller.business.dictionary.batchDelete)
  // 参数配置 config
  router.post('/business/config/list', controller.business.config.list)
  router.post('/business/config/add', controller.business.config.add)
  router.post('/business/config/detail', controller.business.config.detail)
  router.post('/business/config/upsert', controller.business.config.upsert)
  router.post('/business/config/update', controller.business.config.update)
  router.post('/business/config/batchUpdate', controller.business.config.batchUpdate)
  router.post('/business/config/delete', controller.business.config.delete)
  router.post('/business/config/batchDelete', controller.business.config.batchDelete)
  // 自定义接口 customapi
  router.post('/business/customapi/list', controller.business.customapi.list)
  router.post('/business/customapi/add', controller.business.customapi.add)
  router.post('/business/customapi/detail', controller.business.customapi.detail)
  router.post('/business/customapi/update', controller.business.customapi.update)
  router.post('/business/customapi/batchUpdate', controller.business.customapi.batchUpdate)
  router.post('/business/customapi/delete', controller.business.customapi.delete)
  router.post('/business/customapi/batchDelete', controller.business.customapi.batchDelete)
  router.post('/business/customapi/run', controller.business.customapi.run)
  // 我的连接器 myconnector
  router.post('/business/myconnector/list', controller.business.myconnector.list)
  router.post('/business/myconnector/add', controller.business.myconnector.add)
  router.post('/business/myconnector/detail', controller.business.myconnector.detail)
  router.post('/business/myconnector/update', controller.business.myconnector.update)
  router.post('/business/myconnector/batchUpdate', controller.business.myconnector.batchUpdate)
  router.post('/business/myconnector/delete', controller.business.myconnector.delete)
  router.post('/business/myconnector/batchDelete', controller.business.myconnector.batchDelete)

  // 账户 account
  router.post('/auth/account/login', controller.auth.account.login)
  router.post('/auth/account/register', controller.auth.account.register)
  router.post('/auth/account/bind_mobile', controller.auth.account.bind_mobile)
  router.post('/auth/account/bind_email', controller.auth.account.bind_email)
  router.post('/auth/account/bind_wx', controller.auth.account.bind_wx)
  router.post('/auth/account/logout', controller.auth.account.logout)

  // 组织机构 organization
  router.post('/user/organization/list', controller.user.organization.list)
  router.post('/user/organization/add', controller.user.organization.add)
  router.post('/user/organization/detail', controller.user.organization.detail)
  router.post('/user/organization/update', controller.user.organization.update)
  router.post('/user/organization/delete', controller.user.organization.delete)

  // 用户 user
  router.post('/user/list', controller.user.main.list)
  router.post('/user/check_admin', controller.user.main.check_admin)
  router.post('/user/add_admin', controller.user.main.add_admin)
  router.post('/user/add', controller.user.main.add)
  router.post('/user/mine', controller.user.main.mine)
  router.post('/user/detail', controller.user.main.detail)
  router.post('/user/transferSuperAdmin', controller.user.main.transferSuperAdmin)
  router.post('/user/update', controller.user.main.update)
  router.post('/user/batchUpdate', controller.user.main.batchUpdate)
  router.post('/user/delete', controller.user.main.delete)
  router.post('/user/batchDelete', controller.user.main.batchDelete)

  // 用户角色 role
  router.post('/user/role/list', controller.user.role.list)
  router.post('/user/role/add', controller.user.role.add)
  router.post('/user/role/detail', controller.user.role.detail)
  router.post('/user/role/update', controller.user.role.update)
  router.post('/user/role/batchUpdate', controller.user.role.batchUpdate)
  router.post('/user/role/delete', controller.user.role.delete)
  router.post('/user/role/batchDelete', controller.user.role.batchDelete)

  // 用户标签 tag
  router.post('/user/tag/list', controller.user.tag.list)
  router.post('/user/tag/add', controller.user.tag.add)
  router.post('/user/tag/detail', controller.user.tag.detail)
  router.post('/user/tag/update', controller.user.tag.update)
  router.post('/user/tag/batchUpdate', controller.user.tag.batchUpdate)
  router.post('/user/tag/delete', controller.user.tag.delete)
  router.post('/user/tag/batchDelete', controller.user.tag.batchDelete)

  // 权限 permission
  router.post('/user/permission/list', controller.user.permission.list)
  router.post('/user/permission/add', controller.user.permission.add)
  router.post('/user/permission/detail', controller.user.permission.detail)
  router.post('/user/permission/update', controller.user.permission.update)
  router.post('/user/permission/batchUpdate', controller.user.permission.batchUpdate)
  router.post('/user/permission/delete', controller.user.permission.delete)
  router.post('/user/permission/batchDelete', controller.user.permission.batchDelete)

  // 数据表 table
  router.post('/table/list', controller.table.main.list)
  router.post('/table/system_list', controller.table.main.system_list)
  router.post('/table/add', controller.table.main.add)
  router.post('/table/ai_create', controller.table.main.ai_create)
  router.post('/table/detail', controller.table.main.detail)
  router.post('/table/schema', controller.table.main.schema)
  router.post('/table/update_tablename', controller.table.main.update_tablename)
  router.post('/table/publish', controller.table.main.publish)
  router.post('/table/update', controller.table.main.update)
  router.post('/table/batchUpdate', controller.table.main.batchUpdate)
  router.post('/table/delete', controller.table.main.delete)
  router.post('/table/batchDelete', controller.table.main.batchDelete)
  router.post('/table/group/list', controller.table.group.list)
  router.post('/table/group/add', controller.table.group.add)
  router.post('/table/group/detail', controller.table.group.detail)
  router.post('/table/group/update', controller.table.group.update)
  router.post('/table/group/batchUpdate', controller.table.group.batchUpdate)
  router.post('/table/group/delete', controller.table.group.delete)
  router.post('/table/group/batchDelete', controller.table.group.batchDelete)
  router.post('/table/record/list', controller.table.record.list)
  router.post('/table/record/count', controller.table.record.count)
  router.post('/table/record/export', controller.table.record.export)
  router.post('/table/record/import', controller.table.record.import)
  router.post('/table/record/add', controller.table.record.add)
  router.post('/table/record/detail', controller.table.record.detail)
  router.post('/table/record/update', controller.table.record.update)
  router.post('/table/record/batchUpdate', controller.table.record.batchUpdate)
  router.post('/table/record/delete', controller.table.record.delete)
  router.post('/table/record/batchDelete', controller.table.record.batchDelete)
  router.post('/table/index/list', controller.table.index.list)
  router.post('/table/index/add', controller.table.index.add)
  router.post('/table/index/detail', controller.table.index.detail)
  router.post('/table/index/update', controller.table.index.update)
  router.post('/table/index/delete', controller.table.index.delete)
  router.post('/table/virtual/list', controller.table.virtual.list)
  router.post('/table/virtual/add', controller.table.virtual.add)
  router.post('/table/virtual/detail', controller.table.virtual.detail)
  router.post('/table/virtual/update', controller.table.virtual.update)
  router.post('/table/virtual/delete', controller.table.virtual.delete)
  router.post('/table/draft/list', controller.table.draft.list)
  router.post('/table/draft/add', controller.table.draft.add)
  router.post('/table/draft/detail', controller.table.draft.detail)
  router.post('/table/draft/last', controller.table.draft.last)
  router.post('/table/draft/update', controller.table.draft.update)
  router.post('/table/draft/batchUpdate', controller.table.draft.batchUpdate)
  router.post('/table/draft/delete', controller.table.draft.delete)
  router.post('/table/draft/batchDelete', controller.table.draft.batchDelete)

  // 数据记录 namerecord
  router.post('/table/*/record/list', controller.table.namerecord.list)
  router.post('/table/*/record/count', controller.table.namerecord.count)
  router.post('/table/*/record/export', controller.table.namerecord.export)
  router.post('/table/*/record/import', controller.table.namerecord.import)
  router.post('/table/*/record/add', controller.table.namerecord.add)
  router.post('/table/*/record/detail', controller.table.namerecord.detail)
  router.post('/table/*/record/update', controller.table.namerecord.update)
  router.post('/table/*/record/batchUpdate', controller.table.namerecord.batchUpdate)
  router.post('/table/*/record/delete', controller.table.namerecord.delete)
  router.post('/table/*/record/batchDelete', controller.table.namerecord.batchDelete)

  // 资源 resource
  router.post('/resource/list', controller.resource.main.list)
  router.post('/resource/add', controller.resource.main.add)
  router.post('/resource/checkSize', controller.resource.main.checkSize)
  router.post('/resource/detail', controller.resource.main.detail)
  router.post('/resource/update', controller.resource.main.update)
  router.post('/resource/batchUpdate', controller.resource.main.batchUpdate)
  router.post('/resource/delete', controller.resource.main.delete)
  router.post('/resource/batchDelete', controller.resource.main.batchDelete)
  // 网页托管
  router.post('/resource/web/list', controller.resource.web.list)
  router.post('/resource/web/upload', controller.resource.web.upload)
  router.post('/resource/web/mkdir', controller.resource.web.mkdir)
  router.post('/resource/web/add', controller.resource.web.add)
  router.post('/resource/web/delete', controller.resource.web.delete)
  // 资源分组
  router.post('/resource/group/list', controller.resource.group.list)
  router.post('/resource/group/add', controller.resource.group.add)
  router.post('/resource/group/detail', controller.resource.group.detail)
  router.post('/resource/group/update', controller.resource.group.update)
  router.post('/resource/group/batchUpdate', controller.resource.group.batchUpdate)
  router.post('/resource/group/delete', controller.resource.group.delete)
  router.post('/resource/group/batchDelete', controller.resource.group.batchDelete)

  // 日志 log
  router.post('/log/list', controller.log.main.list)
  router.post('/log/add', controller.log.main.add)
  router.post('/log/detail', controller.log.main.detail)
  router.post('/log/update', controller.log.main.update)
  router.post('/log/batchUpdate', controller.log.main.batchUpdate)
  router.post('/log/delete', controller.log.main.delete)
  router.post('/log/batchDelete', controller.log.main.batchDelete)

  // 数据监控 warning
  router.post('/warning/list', controller.warning.main.list)
  router.post('/warning/add', controller.warning.main.add)
  router.post('/warning/detail', controller.warning.main.detail)
  router.post('/warning/update', controller.warning.main.update)
  router.post('/warning/batchUpdate', controller.warning.main.batchUpdate)
  router.post('/warning/delete', controller.warning.main.delete)
  router.post('/warning/batchDelete', controller.warning.main.batchDelete)

  // 消息 message
  router.post('/message/list', controller.message.main.list)
  router.post('/message/count', controller.message.main.count)
  router.post('/message/add', controller.message.main.add)
  router.post('/message/detail', controller.message.main.detail)
  router.post('/message/messageInfo', controller.message.main.messageInfo)
  router.post('/message/update', controller.message.main.update)
  router.post('/message/batchUpdate', controller.message.main.batchUpdate)
  router.post('/message/delete', controller.message.main.delete)
  router.post('/message/batchDelete', controller.message.main.batchDelete)
  router.post('/message/reply/list', controller.message.reply.list)
  router.post('/message/reply/add', controller.message.reply.add)
  router.post('/message/reply/detail', controller.message.reply.detail)
  router.post('/message/reply/update', controller.message.reply.update)
  router.post('/message/reply/batchUpdate', controller.message.reply.batchUpdate)
  router.post('/message/reply/delete', controller.message.reply.delete)
  router.post('/message/reply/batchDelete', controller.message.reply.batchDelete)
  // 通知公告管理
  router.post('/operation/notice/list', controller.operation.notice.list)
  router.post('/operation/notice/add', controller.operation.notice.add)
  router.post('/operation/notice/detail', controller.operation.notice.detail)
  router.post('/operation/notice/update', controller.operation.notice.update)
  router.post('/operation/notice/read', controller.operation.notice.read)
  router.post('/operation/notice/batchUpdate', controller.operation.notice.batchUpdate)
  router.post('/operation/notice/delete', controller.operation.notice.delete)
  router.post('/operation/notice/batchDelete', controller.operation.notice.batchDelete)
  // 消息通知管理
  router.post('/operation/message/list', controller.operation.message.list)
  router.post('/operation/message/add', controller.operation.message.add)
  router.post('/operation/message/detail', controller.operation.message.detail)
  router.post('/operation/message/update', controller.operation.message.update)
  router.post('/operation/message/batchUpdate', controller.operation.message.batchUpdate)
  router.post('/operation/message/delete', controller.operation.message.delete)
  router.post('/operation/message/batchDelete', controller.operation.message.batchDelete)

  // 拓展开发
  router.post('/expand/app/list', controller.expand.app.list)
  router.post('/expand/app/add', controller.expand.app.add)
  router.post('/expand/app/detail', controller.expand.app.detail)
  router.post('/expand/app/update', controller.expand.app.update)
  router.post('/expand/app/batchUpdate', controller.expand.app.batchUpdate)
  router.post('/expand/app/delete', controller.expand.app.delete)
  router.post('/expand/app/batchDelete', controller.expand.app.batchDelete)
  router.post('/expand/token/list', controller.expand.token.list)
  router.post('/expand/token/add', controller.expand.token.add)
  router.post('/expand/token/detail', controller.expand.token.detail)
  router.post('/expand/token/update', controller.expand.token.update)
  router.post('/expand/token/invalidate', controller.expand.token.invalidate)
  router.post('/expand/token/batchUpdate', controller.expand.token.batchUpdate)
  router.post('/expand/token/delete', controller.expand.token.delete)
  router.post('/expand/token/batchDelete', controller.expand.token.batchDelete)
  
  // 无代码应用
  // router.post('/nocode/app/list', controller.nocode.app.list)
  // router.post('/nocode/app/add', controller.nocode.app.add)
  // router.post('/nocode/app/detail', controller.nocode.app.detail)
  // router.post('/nocode/app/update', controller.nocode.app.update)
  // router.post('/nocode/app/delete', controller.nocode.app.delete)
  // router.post('/nocode/appmenu/list', controller.nocode.appmenu.list)
  // router.post('/nocode/appmenu/add', controller.nocode.appmenu.add)
  // router.post('/nocode/appmenu/detail', controller.nocode.appmenu.detail)
  // router.post('/nocode/appmenu/update', controller.nocode.appmenu.update)
  // router.post('/nocode/appmenu/delete', controller.nocode.appmenu.delete)
  // router.post('/nocode/appmenu/createWorkflow', controller.nocode.appmenu.createWorkflow)
  

}

